#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --echo-all --username "$POSTGRES_USER" --dbname "${POSTGRES_DB}" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE USER ${PROJECT_ADMIN};
    ALTER USER ${PROJECT_ADMIN} WITH ENCRYPTED PASSWORD '${PROJECT_PASSWORD}';
    CREATE DATABASE ${PROJECT_DB} OWNER ${PROJECT_ADMIN};
EOSQL

psql -v ON_ERROR_STOP=1 --echo-all --username "$POSTGRES_USER" --dbname "${PROJECT_DB}" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    GRANT ALL PRIVILEGES ON DATABASE ${PROJECT_DB} TO ${PROJECT_ADMIN};
    ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO ${PROJECT_ADMIN};
    ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO ${PROJECT_ADMIN};
EOSQL